my_infra:
  hosts:
    app-dev:
      ansible_host: 192.168.56.101
      ansible_user: admin
      django_debug: true

    app-prod1:
      ansible_host: 192.168.56.102
      ansible_user: admin
      django_debug: false

    jenkins:
      ansible_host: 192.168.56.103
      ansible_user: admin
      django_debug: false
