my_infra:
  hosts:
    app-dev:
      ansible_host: 192.168.56.11
      ansible_user: admin
      django_debug: true

    app-prod1:
      ansible_host: 192.168.56.12
      ansible_user: admin
      django_debug: false
